using Oscar
using Test

include("abelian_aut.jl")
include("describe.jl")
include("spinor_norms.jl")
include("conformance.jl")
include("constructors.jl")
include("operations.jl")
include("elements.jl")
include("quotients.jl")
include("subgroups_and_cosets.jl")
include("conjugation.jl")
include("homomorphisms.jl")
include("libraries.jl")
include("directproducts.jl")
include("matrixgroups.jl")
include("gsets.jl")
include("forms.jl")
include("MatrixDisplay.jl")
include("group_characters.jl")
include("FiniteFormOrthogonalGroup.jl")
include("GrpAb.jl")
include("Permutations.jl")
