coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
    changes:
      default:
        informational: true

comment:
  layout: "header, diff, changes, tree"
  behavior: default
