codecov:
  notify:
    # Keep this in sync with the number of CI jobs uploading coverage.
    after_n_builds: 3
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
    changes:
      default:
        informational: true

comment:
  layout: "header, diff, changes, tree"
  behavior: default
