[FTM-1511-03209]

git-tree-sha1 = "253e96bbc764b7446e5458272ef7e31456fb9ec7"
lazy = true

    [[FTM-1511-03209.download]]
    sha256 = "1fe3db9657a9a4928b34ce5e5772fcd393ba6f27e0da7a87f47c5c054e26678d"
    url = "https://github.com/homalg-project/ToricVarieties_project/releases/download/2022-07-13/1511-03209.tar.gz"

[QSMDB]
git-tree-sha1 = "796900a5e5237f02b2593ff3b2317f63dec2a20f"
lazy = true

     [[QSMDB.download]]
     sha256 = "f64fc541a0168b5e50be3dd6cf2e6c54fb07a5fbdd5abc5894c97e92fef4b704"
     url = "https://github.com/oscar-system/Oscar.jl/releases/download/archive-tag-1/QSMDB-8.tar.gz"

[gap_extraperfect]
git-tree-sha1 = "084fa12573e5089ceb3299f9d341f244b415da52"
lazy = true

    [[gap_extraperfect.download]]
    sha256 = "e565303927682f54cba20a69b8d23673b9b9d4d2a2bc88751f58ed5d3365e29f"
    url = "https://github.com/oscar-system/GAP.jl/releases/download/archive-tag/extraperfect.tar.gz"
    # Created from https://github.com/hulpke/extraperfect using
    # #!/bin/sh
    # export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
    # rm -rf extraperfect
    # mkdir extraperfect
    # gzip -9 -n -c perf27.grp > extraperfect/perf27.grp.gz
    # gzip -9 -n -c perf33.grp > extraperfect/perf33.grp.gz
    # gtar --mtime="$(git log -1 --pretty=%cI)" --owner=0 --group=0 --numeric-owner -cvf extraperfect.tar extraperfect
    # gzip -n -c extraperfect.tar > extraperfect.tar.gz
