# implement some forwarding of functionality for plain maps. 
underlying_map(psi::FiniteExtension) = psi.phi
domain(psi::FiniteExtension{DT}) where DT = domain(underlying_map(psi))::DT
codomain(psi::FiniteExtension{DT, CT}) where {DT, CT} = codomain(underlying_map(psi))::CT
(psi::FiniteExtension)(x) = underlying_map(psi)(x)


### Getters for additional functionality particular to finite extensions
@doc raw"""
    fiber_ideal(psi::FiniteExtension)

Given a finite extension ``ψ : A → B`` of ℤ-graded rings this gives the 
ideal ``I = ⟨x₁,…, xₘ⟩ ⊂ B`` generated by the variables of ``A``. 
"""
function fiber_ideal(psi::FiniteExtension)
  if !isdefined(psi, :fiber_ideal)
    R = codomain(psi)
    psi.fiber_ideal = ideal(R, images_of_generators(psi.phi))
  end
  return psi.fiber_ideal::ideal_type(codomain(psi))
end

@doc raw"""
    fiber_quotient(psi::FiniteExtension)

Given a finite extension ``ψ : A → B`` of ℤ-graded rings return the 
quotient ``B/I`` of the codomain by the `fiber_ideal`.
"""
function fiber_quotient(psi::FiniteExtension)
  if !isdefined(psi, :fiber_quotient)
    Q, _ = quo(codomain(psi), fiber_ideal(psi))
    psi.fiber_quotient = Q
  end
  return psi.fiber_quotient
end

@doc raw"""
    generating_system(psi::FiniteExtension)

Given a finite extension ``ψ : A → B`` of ℤ-graded rings return a 
generating set of ``B`` as an ``A``-module.
"""
function generating_system(psi::FiniteExtension)
  !isdefined(psi, :basis) && codomain_as_module(psi) # fill the cache
  return psi.basis::Vector{elem_type(base_ring(codomain(psi)))}
end

@doc raw"""
    codomain_as_module(psi::FiniteExtension)

Given a finite extension ``ψ : A → B`` of ℤ-graded rings return an 
``A``-module ``M`` which is isomorphic to ``B``.
"""
function codomain_as_module(psi::FiniteExtension)
  if !isdefined(psi, :codomain_as_module)
    phi = underlying_map(psi)
    g, rel, interp = present_finite_extension_ring(phi)
    B = domain(psi)
    R = codomain(psi)
    P = base_ring(R)
    G = grading_group(B)
    F = graded_free_module(B, [degree(Int, x) for x in g])
    rels = isempty(rel) ? elem_type(F)[] : elem_type(F)[sum(rel[i, j]*F[j] for j in 1:ncols(rel); init=zero(F)) for i in 1:nrows(rel)]
    psi.codomain_as_module = SubquoModule(F, gens(F), rels)
    psi.interp = interp
    psi.basis = g
  end
  return psi.codomain_as_module::SubquoModule{elem_type(domain(psi))}
end

@doc raw"""
    pushforward(psi::FiniteExtension, F::FreeMod)

Given a finite extension ``ψ : A → B`` of ℤ-graded rings and a free 
module `F` over ``B``, construct a module ``M`` over ``A`` which is 
isomorphic to ``F`` as an ``A``-module. This returns a pair `(M, interp)` 
where `interp` is a map for the identification ``M → F``.

!!! note
    The name `pushforward` refers to the geometric map ``Spec B → Spec A`` induced by `psi` in the scheme theoretic sense on the spectra of the rings. 
"""
function pushforward(psi::FiniteExtension, F::FreeMod)
  M = codomain_as_module(psi)
  summands = [twist(M, Int(g[1])) for g in degrees_of_generators(F)]
  result, _ = direct_sum(summands...)
  interp = function(v::FreeModElem)
    res = zero(result)
    for (i, c) in coordinates(v)
      inj = canonical_injection(result, i)
      w = psi.interp(lift(c))
      ww = sum(cc*M[j] for (j, cc) in enumerate(w); init=zero(M))
      res += inj(summands[i](coordinates(ww)))
    end
    return res
  end
  interp_inv = function(w::SubquoModuleElem)
    g = generating_system(psi)
    R = codomain(psi)
    res = zero(F)
    phi = underlying_map(psi)
    for i in 1:length(summands)
      pr = canonical_projection(result, i)
      ww = pr(w)
      cw = coordinates(ww)
      res = sum(phi(c)*g[j]*F[i] for (j, c) in cw; init=res)
    end
    return res
  end
  return result, MapFromFunc(F, result, interp, interp_inv)
end

@doc raw"""
    pushforward(psi::FiniteExtension, M::SubquoModule;
        ambient_pushforward=pushforward(psi, ambient_free_module(M))
      )

Given a finite extension ``ψ : A → B`` of ℤ-graded rings and a subquotient 
module `M` over ``B``, construct a module ``N`` over ``A`` which is 
isomorphic to ``M`` as an ``A``-module. This returns a pair `(N, interp)` 
where `interp` is a map for the identification ``N → M``.

!!! note
    The name `pushforward` refers to the geometric map ``Spec B → Spec A`` induced by `psi` in the scheme theoretic sense on the spectra of the rings. 
"""
function pushforward(psi::FiniteExtension, M::SubquoModule;
    ambient_pushforward=pushforward(psi, ambient_free_module(M))
  )
  psiF, interp = ambient_pushforward
  psi_gens = elem_type(psiF)[interp(g*v) for v in ambient_representatives_generators(M) for g in generating_system(psi)]
  psi_rels = elem_type(psiF)[interp(g*v) for v in relations(M) for g in generating_system(psi)]
  I, _ = sub(psiF, psi_gens)
  result, _ = quo(I, psi_rels)
  interp_sq = function(v::SubquoModuleElem)
    w = repres(interp(repres(v)))
    return result(w)
  end
  interp_sq_inv = function(w::SubquoModuleElem)
    v = preimage(interp, psiF(repres(w)))
    return M(v)
  end
  return result, MapFromFunc(M, result, interp_sq, interp_sq_inv)
end

### specialized methods for common functions
# The problem here is that for general gradings there is no working coercion. 
# But we restricted to integer gradings for `FiniteExtension`, so we can work around that. 
function change_base_ring(psi::FiniteExtension, M::SubquoModule)
  F = ambient_free_module(M)
  (ngens(M) == ngens(F) && all(repres(M[i]) == F[i] for i in 1:ngens(F))) || error("module must be presented as cokernel")
  S = domain(psi)
  A = codomain(psi)
  FA = graded_free_module(A, [degree(Int, v) for v in gens(F)])
  I, _ = sub(FA, elem_type(FA)[FA(map_entries(psi, coordinates(v))) for v in relations(M)])
  result, _ = quo(FA, I)
  # the usual hom does not work in the next row because of grading incompatibilities
  return result, MapFromFunc(M, result, v->result(FA(map_entries(underlying_map(psi), coordinates(v)))))
end

### some auxillary functionality which was nowhere to be found
function vector_space_basis(kk::Field, Q::MPolyQuoRing)
  @assert kk === coefficient_ring(Q)
  I = modulus(Q)
  P = base_ring(I)
  SI = singular_generators(groebner_basis(I))
  sb = Singular.kbase(SI)
  return [P(x) for x in gens(sb)]::Vector{elem_type(P)}
end

function _global_section_module(psi::FiniteExtension, M::SubquoModule)
  pf_M, interp = pushforward(psi, M)
end

