@doc raw"""
    FiniteGradedMPolyAnyMap{DomainType, CodomainType} <: Map{DomainType, CodomainType, Map, FiniteGradedMPolyAnyMap}

Type for morphisms of graded algebras ``φ : A → B`` over a field with ``B`` a finite 
``A``-module. This wraps an ordinary homomorphism of rings and extends it with additional 
(cached) data and functionality, such as a generating system of ``B`` over ``A``, etc.
"""
mutable struct FiniteGradedMPolyAnyMap{DomainType, CodomainType} <: Map{DomainType, CodomainType, Map, FiniteGradedMPolyAnyMap}
  phi::MPolyAnyMap{DomainType, CodomainType, Nothing} # the actual underlying morphism
  fiber_ideal::Ideal # the ideal in the codomain generated by the variables of the domain
  fiber_quotient::MPolyQuoRing # the quotient ring for the fiber
  basis::Vector # a generating set of the codomain as a module over the domain
  codomain_as_module::SubquoModule # a module over the domain which is isomorphic to the cod.
  interp # the identification morphism between the codomain and the previous module

  function FiniteGradedMPolyAnyMap(
      phi::MPolyAnyMap{DomainType, CodomainType, Nothing}
    ) where {DomainType, CodomainType}
    dom = domain(phi)
    cod = codomain(phi)
    # For the moment we only support integer gradings. 
    # Gradings are necessary for the theory to work, e.g. that a sequence of elements 
    # which reduce to a vector space basis of the `fiber_quotient` indeed provide a 
    # generating set of the codomain as a module over the domain. The case of local 
    # rings could also be realized, but there has not been an audience for it, yet. 
    #   Morphisms of graded rings still do not have an appropriate framework in Oscar 
    # and this is an ongoing effort of the community. The main open question is whether 
    # and how they should be enhanced by an accompanying morphism of their grading 
    # groups. For gradings by the integers, this morphism should be more or less 
    # straightforward with canonical coercion. 
    @assert is_z_graded(dom) && is_z_graded(cod) "only ZZ-graded domain and codomain are supported"
    return new{DomainType, CodomainType}(phi)
  end
end

