include("types.jl")
include("perm.jl")
include("group_constructors.jl")
include("sub.jl")
include("homomorphisms.jl")
include("cosets.jl")
include("GAPGroups.jl")
include("pcgroup.jl")
include("directproducts.jl")
include("matrices/matrices.jl")
include("matrices/FiniteFormOrthogonalGroup.jl")
include("libraries/libraries.jl")
include("gsets.jl")
include("MatrixDisplay.jl")
include("abelian_aut.jl")
include("spinor_norms.jl")
include("GrpAb.jl")
include("group_characters.jl")  # needs some Rings functionality
include("schur_index.jl")
include("tom.jl")
include("action.jl")  # needs some PolynomialRings functionality
include("recog.jl")
