include("exports.jl")
include("types.jl")

function modular_subgroup(s::PermGroupElem, t::PermGroupElem)
  if !defines_coset_action_s_t(s, t)
    throw(ArgumentError("s and t do not describe the action of the generators S and T on the cosets of a finite-index subgroup of SL(2,Z)"))
  end
  return ModularGroup(s, t, s^-1*t^-1*s, s^-1*t^-1)
end

@doc raw"""
    modular_subgroup_via_right_action(s::PermGroupElem, t::PermGroupElem)

This function constructs a `ModularGroup` object corresponding to the finite-index subgroup
of ``{\rm SL}_2(\mathbb{Z})`` described by the permutations ``s`` and ``t``. This constructor tests if
the given permutations actually describe the (right) coset action of the matrices
```math
S = \begin{pmatrix} 0 & -1 \\ 1 & 0 \end{pmatrix}, \qquad T= \begin{pmatrix} 1 & 1 \\ 0 & 1 \end{pmatrix},
```
by checking that they act transitively and satisfy the relations
``s^4 = (s^3 t)^3 = s^2 t s^{-2} t^{-1} = 1``.

# Examples
```jldoctest
julia> s = cperm([1,2], [3,4], [5,6], [7,8], [9,10])
(1,2)(3,4)(5,6)(7,8)(9,10)

julia> t = cperm([1,4], [2,5,9,10,8], [3,7,6])
(1,4)(2,5,9,10,8)(3,7,6)

julia> G = modular_subgroup_via_right_action(s, t)
Modular subgroup of index 10
```
"""
function modular_subgroup_via_right_action(s::PermGroupElem, t::PermGroupElem)
  return modular_subgroup(s, t)
end

@doc raw"""
    modular_subgroup_via_left_action(s::PermGroupElem, t::PermGroupElem)

Same as `modular_subgroup_via_right_action`, but now the permutations describe the action on
the left cosets.

# Examples
```jldoctest
julia> s = cperm([1,2], [3,4], [5,6], [7,8], [9,10])
(1,2)(3,4)(5,6)(7,8)(9,10)

julia> t = cperm([1,4], [2,5,9,10,8], [3,7,6])
(1,4)(2,5,9,10,8)(3,7,6)

julia> G = modular_subgroup_via_left_action(s, t)
Modular subgroup of index 10
```
"""
function modular_subgroup_via_left_action(s::PermGroupElem, t::PermGroupElem)
  return modular_subgroup(s^-1, t^-1)
end

function Base.:(==)(G::ModularGroup, H::ModularGroup)
  return index(G) == index(H) && issubset(G, H)
end

function Base.hash(G::ModularGroup, h::UInt)
  s = s_right_perm(G)
  t = t_right_perm(G)
  return hash((index(G), cycle_structure(s), cycle_structure(t), cycle_structure(s * t)), h)
end

function Base.show(io::IO, G::ModularGroup)
  idx = index(G)
  print(io, "Modular subgroup of index $(idx)")
end

function Base.print(io::IO, G::ModularGroup)
  idx = index(G)
  s = s_right_perm(G)
  t = t_right_perm(G)
  r = r_right_perm(G)
  j = j_right_perm(G)
  print(io, "ModularSubgroup(\n S : $(s)\n T : $(t)\n R : $(r)\n J : $(j) )")
end

@doc raw"""
    s_right_perm(G::ModularGroup)

Returns the permutation describing the action of the matrix ``S = \begin{pmatrix} 0 & -1 \\ 1 & 0 \end{pmatrix}``
on the right cosets of `G`.
"""
function s_right_perm(G::ModularGroup)
  return G.s
end

@doc raw"""
    t_right_perm(G::ModularGroup)

Returns the permutation describing the action of the matrix ``T= \begin{pmatrix} 1 & 1 \\ 0 & 1 \end{pmatrix}``
on the right cosets of `G`.
"""
function t_right_perm(G::ModularGroup)
  return G.t
end

@doc raw"""
    r_right_perm(G::ModularGroup)

Returns the permutation describing the action of the matrix ``R= \begin{pmatrix} 1 & 0 \\ 1 & 1 \end{pmatrix}``
on the right cosets of `G`.
"""
function r_right_perm(G::ModularGroup)
  return G.r
end

@doc raw"""
    j_right_perm(G::ModularGroup)

Returns the permutation describing the action of the matrix ``J= \begin{pmatrix} 0 & 1 \\ -1 & 1 \end{pmatrix}``
on the right cosets of `G`.
"""
function j_right_perm(G::ModularGroup)
  return G.j
end

function defines_coset_action_s_t(s::PermGroupElem, t::PermGroupElem)
  isone(s^4) || return false
  isone((s^3*t)^3) || return false
  isone(s^2*t*s^-2*t^-1) || return false
  idx = maximum([maximum(moved_points(s); init=1), maximum(moved_points(t); init=1)])
  return is_transitive(permutation_group(idx, [s, t]))
end

@attr Int function index(G::ModularGroup)
  return maximum([maximum(moved_points(s_right_perm(G)); init=1), maximum(moved_points(t_right_perm(G)); init=1)])::Int
end

const _SL2Z_FP_CACHE = Ref{Tuple{FPGroup, FPGroupElem, FPGroupElem}}()

# cache the SL2Z presentation so that it can be reused consistently
# (especially in testing)
function _SL2Z_fp()
  if !isassigned(_SL2Z_FP_CACHE)
    F = free_group(["S", "T"])
    S, T = gens(F)

    SL2Z, _ = quo(F, [S^4, (S^3*T)^3, S^2*T*S^-2*T^-1])

    S, T = gens(SL2Z)

    _SL2Z_FP_CACHE[] = (SL2Z, S, T)
  end

  return _SL2Z_FP_CACHE[]::Tuple{FPGroup, FPGroupElem, FPGroupElem}
end

# cache the permutation group generated by s and t
@attr PermGroup function _perm_group(G::ModularGroup)
  return sub(symmetric_group(index(G)), [s_right_perm(G), t_right_perm(G)])[1]
end

# cache the homomorphism from SL2Z to P
@attr GAPGroupHomomorphism{FPGroup, PermGroup} function _coset_action_hom(G::ModularGroup)
  SL2Z, _, _ = _SL2Z_fp()
  P = _perm_group(G)
  return hom(SL2Z, P, [s_right_perm(G), t_right_perm(G)])
end

function word_gens(G::ModularGroup)

  P = _perm_group(G)
  phi = _coset_action_hom(G)

  # TODO: might need to check whether this is efficient enough for large index
  Hperm, _ = stabilizer(P, 1)

  H, inc = preimage(phi, Hperm)

  return [inc(h) for h in gens(H)]
end

function gens(G::ModularGroup)
  w_gens = word_gens(G)

  MatS = matrix(ZZ, [0 -1; 1 0])
  MatT = matrix(ZZ, [1  1; 0 1])

  M = matrix_group([MatS, MatT])
  MS, MT = gens(M)

  SL2Z, _, _ = _SL2Z_fp()
  phi = hom(SL2Z, M, [MS, MT])

  return [matrix(phi(w)) for w in w_gens]
end

function s_t_decomposition(M::ZZMatrix)
  if det(M) != 1
    throw(ArgumentError("Matrix needs to be in SL(2, Z)"))
  end

  MatS = matrix(ZZ, [0 -1; 1 0])
  MatT = matrix(ZZ, [1  1; 0 1])

  SL2Z, S, T = _SL2Z_fp()
  
  decomp = one(SL2Z)

  while M[2, 1] != 0
    k = div(M[2, 2], M[2, 1])
    decomp = S^-1 * T^k * decomp
    M = M * MatT^-k * MatS
  end

  # now M[2, 1] = 0 and since det(M) == 1, we have M == +-T^r where r = M[1, 2]
  if M[1, 1] == 1
    decomp = T^M[1, 2] * decomp
  else
    decomp = S^2 * T^-M[1, 2] * decomp
  end

  return decomp
end

function coset_action_of(A::ZZMatrix, G::ModularGroup)
  @req isone(det(A)) "Matrix needs to be in SL(2, Z)"
  w = s_t_decomposition(A)
  phi = _coset_action_hom(G)
  return phi(w)
end

function coset_right_action_of(A::ZZMatrix, G::ModularGroup)
  return coset_action_of(A, G)
end

function coset_left_action_of(A::ZZMatrix, G::ModularGroup)
  return coset_action_of(A, G)^-1
end

function Base.in(A::ZZMatrix, G::ModularGroup)
    if det(A) != 1
      return false
    end
    return coset_action_of(A, G)(1) == 1
end

function is_word_elm_of(w::FPGroupElem, G::ModularGroup)
  phi = _coset_action_hom(G)
  return phi(w)(1) == 1
end

function Base.issubset(H::ModularGroup, G::ModularGroup)
  return all(A -> A in G, gens(H))
end
