@doc raw"""
    slack_ideal_non_saturated(P::Polyhedron)

Compute the (non-saturated) slack ideal of the input polytope `P` as described
in [GMTW19](@cite).

To get the slack ideal one needs to saturate this ideal, which can be
expensive.

Optionally one can pass a suitable polynomial ring as the first argument.

# Examples
```jldoctest
julia> c = cube(2)
Polytope in ambient dimension 2

julia> slack_ideal_non_saturated(c)
Ideal generated by
  x1*x4*x6*x7 - x2*x3*x5*x8
```
"""
function slack_ideal_non_saturated(P::Polyhedron)
  pmo = pm_object(P)
  SM = pmo.SLACK_MATRIX
  Rnvars = count(!iszero, vec(SM))
  R, x = polynomial_ring(QQ, Rnvars; cached=false)
  return slack_ideal_non_saturated(R, P)
end

function slack_ideal_non_saturated(R::MPolyRing, P::Polyhedron)
  pmo = pm_object(P)
  SM = pmo.SLACK_MATRIX
  Rnvars = count(!iszero, vec(SM))
  @req nvars(R) == Rnvars "Wrong number of variables in R. Should be $Rnvars."
  x = gens(R)
  VM = zero_matrix(R, nrows(SM), ncols(SM))
  c = 1
  for i in 1:nrows(SM)
    for j in 1:ncols(SM)
      if !iszero(SM[i, j])
        VM[i, j] = x[c]
        c += 1
      end
    end
  end
  return ideal(minors(VM, dim(P) + 2))
end

function slack_ideal(R::MPolyRing, P::Polyhedron)
  result = slack_ideal_non_saturated(R, P)
  p = ideal(prod(gens(R)))
  return saturation(result, p)
end

@doc raw"""
    slack_ideal(P::Polyhedron)

Compute the slack ideal of the input polytope `P` as described in [GMTW19](@cite).

Optionally one can pass a suitable polynomial ring as the first argument.

# Examples
```jldoctest
julia> c = cube(2)
Polytope in ambient dimension 2

julia> slack_ideal(c)
Ideal generated by
  x1*x4*x6*x7 - x2*x3*x5*x8
```
"""
function slack_ideal(P::Polyhedron)
  result = slack_ideal_non_saturated(P)
  p = ideal(prod(gens(base_ring(result))))
  return saturation(result, p)
end
