include("GaloisGrp.jl")
include("Rings.jl")
include("ModStd.jl")
include("PlaneCurve.jl")
include("InvariantTheory.jl")
include("GITFans.jl")
include("GModule.jl")
include("MPolyRingSparse.jl")

include("Schemes/AffineSchemes.jl")
include("Schemes/SpecOpen.jl")
include("Schemes/Glueing.jl")
include("Schemes/ProjectiveSchemes.jl")
include("Schemes/CoveredScheme.jl")
include("Schemes/AffineCurve.jl")
include("Schemes/IdealSheaves.jl")
include("Schemes/CoherentSheaves.jl")

include("Matrix/matrix.jl")
