include("GaloisGrp.jl")
include("Rings.jl")
include("ModStd.jl")
include("PlaneCurve.jl")
include("GITFans.jl")
include("GModule.jl")
include("MPolyRingSparse.jl")

include("Schemes/AffineSchemes.jl")
include("Schemes/SpecOpen.jl")
include("Schemes/Glueing.jl")
include("Schemes/SpecialTypes.jl")
include("Schemes/ProjectiveSchemes.jl")
include("Schemes/CoveredScheme.jl")
include("Schemes/ProjectiveModules.jl")
include("Schemes/singular_locus.jl")
include("Schemes/FurtherFunctionality.jl")

include("Matrix/matrix.jl")
