include("GaloisGrp.jl")
include("Rings.jl")
include("ModStd.jl")
include("PlaneCurve.jl")
include("InvariantTheory.jl")
include("GITFans.jl")
include("GModule.jl")

include("Schemes/AffineSchemes.jl")
include("Schemes/SpecOpen.jl")
include("Schemes/Glueing.jl")
include("Schemes/ProjectiveSchemes.jl")
include("Schemes/CoveredScheme.jl")
include("Schemes/IdealSheaves.jl")
include("Schemes/WeilDivisor.jl")
include("Schemes/CoveredProjectiveSchemes.jl")
include("Schemes/VectorBundle.jl")
include("Schemes/smoothness_tests.jl")
