export augmentation_map
export can_compute_index
export can_compute_horizontal_map
export can_compute_vertical_map
export has_horizontal_map
export has_index
export has_vertical_map
export has_left_bound
export has_lower_bound
export has_right_bound
export has_upper_bound
export horizontal_direction
export horizontal_map
export is_complete
export left_bound
export linear_strand
export lower_bound
export map_from_original_complex
export map_to_original_complex
export right_bound
export total_complex
export upper_bound
export vertical_direction
export vertical_map


