# This code uses Derksen's algorithm [Der99] to compute fundamental invariants
# of linearly reductive groups.
# We first set up a LinearlyReductiveGroup, then we set up a representation via
# which the group acts on a vector space (RepresentationLinearlyReductiveGroup).
# Then we set up the invariant ring of the group. The fundamental invariants are
# computed using Derksen's algorithm.
# As of now, the only Reynolds operator that is implemented is the one for SLm,
# using Cayley's Omega process.

################################################################################
#
#  Linearly reductive groups
#
################################################################################

# As of now, linearly reductive groups are only implemented for SLn, its direct
# products and tensors.

function Base.show(io::IO, ::MIME"text/plain", G::LinearlyReductiveGroup)
  io = pretty(io)
  if isdefined(G, :group)
    println(io, "Linearly reductive group ", group_type(G), group_dim(G))
    print(terse(io), Indent(), "over ", Lowercase(), base_ring(G))
    print(io, Dedent())
  else
    println(io, "Linearly reductive group defined by")
    print(io, Indent(), Lowercase(), defining_ideal(G))
    print(io, Dedent())
  end
end

function Base.show(io::IO, G::LinearlyReductiveGroup)
  if is_terse(io)
    print(io, "Linearly reductive group")
  else
    print(io, "Linearly reductive group")
    if isdefined(G, :group)
      print(io, " ", group_type(G), "(", group_dim(G), ",")
      print(terse(io), base_ring(G))
      print(io, ")")
    end
  end
end

@doc raw"""
    linearly_reductive_group(sym::Symbol, m::Int, K::Field)

Return the linearly reductive group indicated by `sym`.

Currently, the supported options for `sym` are:
* `:SL`, corresponding to the special linear group (of degree $m$ over the field $K$).

# Examples
```jldoctest
julia> G = linearly_reductive_group(:SL, 2, QQ)
Linearly reductive group SL2
  over QQ

julia> defining_ideal(G)
Ideal generated by
  z[1, 1]*z[2, 2] - z[2, 1]*z[1, 2] - 1
```
"""
linearly_reductive_group(sym::Symbol, m::Int, F::Field) = LinearlyReductiveGroup(sym, m, F)

@doc raw"""
    linearly_reductive_group(sym::Symbol, m::Int, R::MPolyRing)

Return the linearly reductive group indicated by `sym`.

Currently, the supported options for `sym` are:
* `:SL`, corresponding to the special linear group (of degree $m$ over the base field $K$ of $R$, where $R$ is the polynomial ring in which the defining ideal of SL$(m, K)$ lives).

# Examples
```jldoctest
julia> S, z = polynomial_ring(QQ, :c=> (1:2, 1:2));

julia> G = linearly_reductive_group(:SL,2,S)
Linearly reductive group SL2
  over QQ

julia> defining_ideal(G)
Ideal generated by
  c[1, 1]*c[2, 2] - c[2, 1]*c[1, 2] - 1
```
"""
linearly_reductive_group(sym::Symbol, m::Int, R::MPolyRing) =
  LinearlyReductiveGroup(sym, m, R)

linearly_reductive_group(I::MPolyIdeal) = LinearlyReductiveGroup(I)

base_ring(G::LinearlyReductiveGroup) = G.field
defining_ideal(G::LinearlyReductiveGroup) = G.defining_ideal
canonical_representation(G::LinearlyReductiveGroup) = G.canonical_representation
natural_representation(G::LinearlyReductiveGroup) = G.canonical_representation
group_type(G::LinearlyReductiveGroup) = isdefined(G, :group) ? G.group[1] : nothing
group_dim(G::LinearlyReductiveGroup) = isdefined(G, :group) ? G.group[2] : nothing

################################################################################
#
#  Representations of linearly reductive groups
#
################################################################################

representation_reductive_group(G::LinearlyReductiveGroup, M::MatElem) =
  RepresentationLinearlyReductiveGroup(G, M)
group(R::RepresentationLinearlyReductiveGroup) = R.group
representation_matrix(R::RepresentationLinearlyReductiveGroup) = R.rep_mat
vector_space_dim(R::RepresentationLinearlyReductiveGroup) = ncols(R.rep_mat)

@doc raw"""
    representation_on_forms(G::LinearlyReductiveGroup, d::Int)

If `G` is the special linear group acting by linear substitution on, say, `n`-ary forms of degree `d`, return the corresponding representation.

!!! note
    In accordance with classical papers, an $n$-ary form of degree $d$ in $K[x_1, \dots, x_n]$ is written as a $K$-linear combination
    of the $K$-basis with elements $\binom{d}{I}x^I$. Here, $I = (i_1, \dots, i_n)\in\mathbb Z_{\geq 0}^n$ with $i_1+\dots +i_n =d$.

# Examples
```jldoctest
julia> G = linearly_reductive_group(:SL, 2, QQ);

julia> r = representation_on_forms(G, 2)
Representation
  of linearly reductive group SL(2,QQ)
  on symmetric forms of degree 2

julia> representation_matrix(r)
[      z[1, 1]^2                   2*z[1, 1]*z[2, 1]         z[2, 1]^2]
[z[1, 1]*z[1, 2]   z[1, 1]*z[2, 2] + z[2, 1]*z[1, 2]   z[2, 1]*z[2, 2]]
[      z[1, 2]^2                   2*z[1, 2]*z[2, 2]         z[2, 2]^2]
```
"""
function representation_on_forms(G::LinearlyReductiveGroup, d::Int)
  @req group_type(G) === :SL "Only implemented for SLm"
  return RepresentationLinearlyReductiveGroup(G, d)
end

function representation_reductive_group(G::LinearlyReductiveGroup)
  @req group_type(G) === :SL "Only implemented for SLm"
  M = canonical_representation(G)
  return RepresentationLinearlyReductiveGroup(G, M)
end

function Base.show(io::IO, ::MIME"text/plain", R::RepresentationLinearlyReductiveGroup)
  io = pretty(io)
  println(io, "Representation")
  println(io, Indent(), "of ", Lowercase(), group(R))
  if R.sym_deg[1]
    print(io, "on symmetric forms of degree ", R.sym_deg[2])
    print(io, Dedent())
  else
    println(io, "with representation matrix")
    show(io, representation_matrix(R))
    print(io, Dedent())
  end
end

function Base.show(io::IO, R::RepresentationLinearlyReductiveGroup)
  if is_terse(io)
    print(io, "Representation of linearly reductive group")
  else
    # I don't know what else to print here
    print(io, "Representation of linearly reductive group")
  end
end

function _direct_sum(
  X::RepresentationLinearlyReductiveGroup, Y::RepresentationLinearlyReductiveGroup
)
  @req group(X) === group(Y) "not compatible"
  G = group(X)
  R = base_ring(defining_ideal(G))
  Mat = block_diagonal_matrix(
    R, [Matrix(representation_matrix(X)), Matrix(representation_matrix(Y))]
  )
  return RepresentationLinearlyReductiveGroup(G, Mat)
end

function _direct_sum(V::Vector{RepresentationLinearlyReductiveGroup})
  n = length(V)
  G = group(V[1])
  for i in 2:n
    @req G === group(V[i]) "not compatible"
  end
  R = base_ring(defining_ideal(G))
  Mat = block_diagonal_matrix(R, [Matrix(representation_matrix(V[i])) for i in 1:n])
  return RepresentationLinearlyReductiveGroup(G, Mat)
end

function _tensor_product(
  X::RepresentationLinearlyReductiveGroup, Y::RepresentationLinearlyReductiveGroup
)
  @req group(X) === group(Y) "not compatible"
  Mat = kronecker_product(representation_matrix(X), representation_matrix(Y))
  return RepresentationLinearlyReductiveGroup(group(X), Mat)
end

function _tensor_product(V::Vector{RepresentationLinearlyReductiveGroup})
  n = length(V)
  for i in 2:n
    @req group(V[1]) === group(V[i]) "not compatible"
  end
  Mat = representation_matrix(V[1])
  for i in 2:n
    Mat = kronecker_product(Mat, representation_matrix(V[i]))
  end
  return RepresentationLinearlyReductiveGroup(group(V[1]), Mat)
end

# Compute the representation matrices of SL_m acting over m-forms of symmetric
# degree sym_deg
function _rep_mat(G::LinearlyReductiveGroup, sym_deg::Int)
  group_type(G) === :SL || error("Only implemented for SLm")
  m = group_dim(G)
  R = base_ring(defining_ideal(G))
  mixed_ring, t = polynomial_ring(R, :t => 1:m; cached=false)
  group_mat = natural_representation(G)
  new_vars = group_mat * t

  b = [
    multinomial_coefficient(sym_deg, first(AbstractAlgebra.exponent_vectors(a))) * a for
    a in monomials_of_degree(mixed_ring, sym_deg)
  ]
  n = length(b)

  # transform the b elements
  images_of_b = [evaluate(f, new_vars) for f in b]

  mat = zero_matrix(R, n, n)
  for j in 1:n
    f = images_of_b[j]
    x = mixed_ring()
    # express f as a linear combination of elements in b
    for i in 1:n
      c = coeff(f, leading_exponent(b[i]))
      mat[i, j] = c / leading_coefficient(b[i])
    end
  end
  return mat
end

function multinomial_coefficient(n::Int, v::AbstractVector{<:IntegerUnion})
  x = prod(factorial(ZZ(k)) for k in v)
  return divexact(factorial(ZZ(n)), x)
end

################################################################################
#
#  Invariant rings of linearly reductive groups
#
################################################################################

@doc raw"""
    invariant_ring(r::RepresentationLinearlyReductiveGroup)

Return the invariant ring under the action defined by the representation `r` on an implicitly generated polynomial ring of appropriate dimension.

# Examples
```jldoctest
julia> G = linearly_reductive_group(:SL, 2, QQ);

julia> r = representation_on_forms(G, 2);

julia> RG = invariant_ring(r)
Invariant ring
  of graded multivariate polynomial ring in 3 variables over QQ
  under group action of linearly reductive group SL(2,QQ)
```
"""
invariant_ring(R::RepresentationLinearlyReductiveGroup) = RedGroupInvarRing(R)

@doc raw"""
    invariant_ring(R::MPolyDecRing, r::RepresentationLinearlyReductiveGroup)

Return the invariant subring of `R` under the action induced by the representation of `r` on `R`.

# Examples
```jldoctest
julia> G = linearly_reductive_group(:SL, 3, QQ);

julia> r = representation_on_forms(G, 3);

julia> S, x = graded_polynomial_ring(QQ, :x => 1:10);

julia> RG = invariant_ring(S, r)
Invariant ring
  of graded multivariate polynomial ring in 10 variables over QQ
  under group action of linearly reductive group SL(3,QQ)
```
"""
invariant_ring(ring::MPolyDecRing, R::RepresentationLinearlyReductiveGroup) =
  RedGroupInvarRing(R, ring)

# Cached, as this elimination is the expensive step of Derksen's algorithm.
@attr Tuple{
  MPolyIdeal{mpoly_type(FldT)},dense_matrix_type(mpoly_type(FldT))
} function proj_of_image_ideal(R::RedGroupInvarRing{FldT}) where {FldT}
  Z = representation(R)
  return proj_of_image_ideal(group(Z), Z.rep_mat)
end

@attr ideal_type(PolyRingT) function null_cone_ideal(
  R::RedGroupInvarRing{FldT,PolyRingElemT,PolyRingT}
) where {FldT,PolyRingElemT,PolyRingT}
  I, _ = proj_of_image_ideal(R)
  return _null_cone_ideal(I, vector_space_dim(representation(R)))
end

polynomial_ring(R::RedGroupInvarRing) = R.poly_ring
group(R::RedGroupInvarRing) = R.group
representation(R::RedGroupInvarRing) = R.representation
coefficient_ring(R::RedGroupInvarRing) = R.field

@doc raw"""
    fundamental_invariants(RG::RedGroupInvarRing)

Return a system of fundamental invariants for `RG`.

# Examples
```jldoctest
julia> G = linearly_reductive_group(:SL, 2, QQ);

julia> r = representation_on_forms(G, 2);

julia> RG = invariant_ring(r);

julia> fundamental_invariants(RG)
1-element Vector{MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}}:
 -X[1]*X[3] + X[2]^2

```
"""
function fundamental_invariants(z::RedGroupInvarRing)
  if !isdefined(z, :fundamental)
    b, M = proj_of_image_ideal(z)
    if isdefined(group(z), :group)
      z.fundamental = inv_generators(
        null_cone_ideal(z), group(z), polynomial_ring(z), M, z.reynolds_operator
      )
    else
      z.fundamental = inv_gens_no_reynolds(null_cone_ideal(z), b, polynomial_ring(z))
    end
  end
  return copy(z.fundamental)
end

function Base.show(io::IO, ::MIME"text/plain", R::RedGroupInvarRing)
  io = pretty(io)
  println(io, "Invariant ring")
  println(io, Indent(), "of ", Lowercase(), polynomial_ring(R))
  print(io, "under group action of ", Lowercase(), group(R))
  print(io, Dedent())
end

function Base.show(io::IO, R::RedGroupInvarRing)
  if is_terse(io)
    print(io, "Invariant ring")
  else
    io = pretty(io)
    print(io, "Invariant ring of ")
    print(terse(io), Lowercase(), group(R))
  end
end

#computing the graph Gamma from Derksens paper
function image_ideal(G::LinearlyReductiveGroup, rep_mat::MatElem)
  R = base_ring(rep_mat)
  n = ncols(rep_mat)
  if isdefined(G, :group)
    m = (group_dim(G))^2
  else
    m = ngens(base_ring(defining_ideal(G)))
  end
  mixed_ring_xy, x, y, zz = polynomial_ring(
    base_ring(G), :x => 1:n, :y => 1:n, :zz => 1:m; cached=false
  )
  ztozz = hom(R, mixed_ring_xy, zz)
  genss = [ztozz(f) for f in gens(defining_ideal(G))]
  #rep_mat in the new ring
  new_rep_mat = map_entries(ztozz, rep_mat)
  new_vars = new_rep_mat * x
  ideal_vect = y - new_vars
  ideal_vect = vcat(ideal_vect, genss)
  return ideal(mixed_ring_xy, ideal_vect), new_rep_mat
end

#computing I_{\Bar{B}}
function proj_of_image_ideal(G::LinearlyReductiveGroup, rep_mat::MatElem)
  W = image_ideal(G, rep_mat)
  mixed_ring_xy = base_ring(W[2])
  n = ncols(rep_mat)
  return eliminate(W[1], gens(mixed_ring_xy)[((2 * n) + 1):end]), W[2]
end

#this function gets the null cone ideal, given by a minimal generating set.
#the generators may or may not be invariant.
#to do this we evaluate what is returned from proj_of_image_ideal at y = 0 
#ie at gens(basering)[n+1:2*n] = [0 for i in 1:n]
function _null_cone_ideal(X::MPolyIdeal, n::Int)
  mixed_ring_xy = base_ring(X)
  #evaluate at gens(mixed_ring_xy)[n+1:2*n] = 0
  xyz = gens(mixed_ring_xy)
  V = vcat(xyz[1:n], [0 for i in 1:n], xyz[(2 * n + 1):end])
  ev_gbasis = [evaluate(f, V) for f in gens(X)]
  #grading starts here. In the end, our invariant ring is graded.
  mixed_ring_graded, _ = grade(mixed_ring_xy)
  mapp = hom(mixed_ring_xy, mixed_ring_graded, gens(mixed_ring_graded))
  I = ideal(mixed_ring_graded, elem_type(mixed_ring_graded)[mapp(f) for f in ev_gbasis])
  # the ring is passed as there are no generators if I is zero
  return ideal(mixed_ring_graded, minimal_generating_set(I))
end

# Computing the invariant generators of the null cone by applying reynolds
# operator to gens(I). This is done in K[X,Y] (basering(I)).
# The elements returned will be in the polynomial K[X] (ringg).
function inv_generators(
  I::MPolyIdeal,
  G::LinearlyReductiveGroup,
  ringg::MPolyRing,
  M::MatElem,
  reynolds_function::Function,
)
  genss = gens(I)
  if length(genss) == 0
    return Vector{elem_type(ringg)}()
  end

  #we need the representation matrix and determinant of group matrix to be in basering(I)
  mixed_ring_xy = parent(genss[1])
  R = base_ring(M)
  n = ncols(M)
  m = G.group[2]
  xyz = gens(mixed_ring_xy)
  mapp = hom(R, mixed_ring_xy, xyz)
  new_rep_mat = matrix(mixed_ring_xy, n, n, [mapp(M[i, j]) for i in 1:n, j in 1:n])
  det_ = det(G.canonical_representation)
  mapp_ = hom(parent(det_), mixed_ring_xy, xyz[((2 * n) + 1):end])
  new_det = mapp_(det_)

  #now we apply reynolds operator to genss
  if group_type(G) === :SL #TODO other types of reductive groups
    new_gens_wrong_ring = [reynolds_function(g, new_rep_mat, new_det, m) for g in genss]
  else
    return nothing
  end

  #map them to the required ring, ringg.
  img_genss = vcat(gens(ringg), Hecke.zeros_array(ringg, length(xyz) - n))
  mixed_to_ring = hom(mixed_ring_xy, ringg, img_genss)
  new_gens = Vector{elem_type(ringg)}()
  for elemm in new_gens_wrong_ring
    if !is_zero(elemm)
      push!(new_gens, mixed_to_ring(elemm))
    end
  end

  #remove ugly coefficients:
  return map(_remove_content, new_gens)
end

# Over QQ, scale f by a positive number such that its coefficients become
# coprime integers.
_remove_content(f::MPolyRingElem) = f

function _remove_content(f::MPolyRingElem{QQFieldElem})
  c = reduce(gcd, coefficients(f); init=zero(QQ))
  return is_zero(c) ? f : inv(c) * f
end

# The Reynolds operator for SLm acting via new_rep_mat.
function reynolds_v_slm(
  elem::MPolyDecRingElem, new_rep_mat::MatElem, new_det::MPolyDecRingElem, m::Int
)
  mixed_ring_xy = parent(elem)
  n = ncols(new_rep_mat)
  new_vars = new_rep_mat * gens(mixed_ring_xy)[1:n]
  # new_vars need not be homogeneous, so this is not a map of graded rings
  sum_ = evaluate(elem, vcat(new_vars, [mixed_ring_xy() for i in 1:(n + m^2)]))

  # The Omega process applies to one degree in the z_ij at a time; the parts of
  # degree not divisible by m are mapped to 0.
  res = mixed_ring_xy()
  for (t, f) in _components_by_z_degree(sum_, m)
    is_divisible_by(t, m) || continue
    res += reynolds_slm(f, new_det, divexact(t, m))
  end
  return res
end

# Reynolds operator for SLm using Cayleys Omega process
function reynolds_slm(elem::MPolyRingElem, det_::MPolyRingElem, p::Int)
  num = omegap_(p, det_, elem)
  den = omegap_(p, det_, det_^p)
  if !(denominator(num//den) == 1)
    error("denominator of reynolds not rational")
  end
  return numerator(num//den)
end

# Split elem into its homogeneous components with respect to the degree in the
# z_ij, which are the last m^2 variables of the ring.
function _components_by_z_degree(elem::MPolyDecRingElem, m::Int)
  R = parent(elem)
  n = ngens(R) - m^2
  ctxs = Dict{Int,MPolyBuildCtx}()
  for (c, e) in zip(coefficients(elem), exponents(elem))
    ctx = get!(() -> MPolyBuildCtx(R), ctxs, sum(@view e[(n + 1):end]))
    push_term!(ctx, c, e)
  end
  return Dict(t => finish(ctx) for (t, ctx) in ctxs)
end

function omegap_(p::Int, det_::MPolyDecRingElem, f::MPolyDecRingElem)
  parent(det_) == parent(f) || error("Omega process ring error")
  action_ring = parent(det_)
  monos = collect(monomials(det_))
  coeffs = collect(coefficients(det_))
  for i in 1:p
    h = action_ring()
    for i in 1:length(monos)
      exp_vect = exponent_vector(monos[i], 1)
      x = f
      for i in 1:length(exp_vect), j in 1:exp_vect[i]
        x = derivative(x, i)
        iszero(x) && break
      end
      h += coeffs[i] * x
    end
    f = h
  end
  return f
end

# Return the image of elem under the reynolds operator of group with representation X
function reynolds_operator(X::RepresentationLinearlyReductiveGroup, elem::MPolyRingElem)
  group_type(group(X)) === :SL || error("Only implemented for SLm")
  vector_ring = parent(elem)
  G = X.group
  n = ngens(vector_ring)
  n == ncols(X.rep_mat) || error("group not compatible with element")
  m = group_dim(G)
  R, _ = graded_polynomial_ring(
    base_ring(G), :x => 1:n, :y => 1:n, :z => (1:m, 1:m); cached=false
  )
  map1 = hom(vector_ring, R, gens(R)[1:n])
  new_elem = map1(elem)
  group_ring = base_ring(X.rep_mat)
  map2 = hom(group_ring, R, gens(R)[(2 * n + 1):(2 * n + m^2)])
  new_rep_mat = map_entries(map2, X.rep_mat)
  new_det = map2(det(G.canonical_representation))
  f = X.reynolds_v(new_elem, new_rep_mat, new_det, m)
  reverse_map = hom(R, vector_ring, vcat(gens(vector_ring), [0 for i in 1:(n + m^2)]))
  return reverse_map(f)
end

@doc raw"""
    reynolds_operator(RG::RedGroupInvarRing, f::MPolyRingElem)

Return the image of `f` under the Reynolds operator corresponding to `RG`.

# Examples
```jldoctest
julia> G = linearly_reductive_group(:SL, 3, QQ);

julia> r = representation_on_forms(G, 3);

julia> S, x = graded_polynomial_ring(QQ, :x => 1:10);

julia> RG = invariant_ring(S, r);

julia> 75*reynolds_operator(RG, x[5]^4)
x[1]*x[4]*x[8]*x[10] - x[1]*x[4]*x[9]^2 - x[1]*x[5]*x[7]*x[10] + x[1]*x[5]*x[8]*x[9] + x[1]*x[6]*x[7]*x[9] - x[1]*x[6]*x[8]^2 - x[2]^2*x[8]*x[10] + x[2]^2*x[9]^2 + x[2]*x[3]*x[7]*x[10] - x[2]*x[3]*x[8]*x[9] + x[2]*x[4]*x[5]*x[10] - x[2]*x[4]*x[6]*x[9] - 2*x[2]*x[5]^2*x[9] + 3*x[2]*x[5]*x[6]*x[8] - x[2]*x[6]^2*x[7] - x[3]^2*x[7]*x[9] + x[3]^2*x[8]^2 - x[3]*x[4]^2*x[10] + 3*x[3]*x[4]*x[5]*x[9] - x[3]*x[4]*x[6]*x[8] - 2*x[3]*x[5]^2*x[8] + x[3]*x[5]*x[6]*x[7] + x[4]^2*x[6]^2 - 2*x[4]*x[5]^2*x[6] + x[5]^4
```
"""
function reynolds_operator(R::RedGroupInvarRing, elem::MPolyRingElem)
  X = R.representation
  return reynolds_operator(X, elem)
end

@doc raw"""
    affine_algebra(RG::RedGroupInvarRing)

Return the invariant ring `RG` as an affine algebra (this amounts to compute the algebra syzygies among the fundamental invariants of `RG`).

In addition, if `A` is this algebra, and `R` is the polynomial ring of which `RG` is a subalgebra,
return the inclusion homomorphism  `A` $\hookrightarrow$ `R` whose image is `RG`.

# Examples
```jldoctest
julia> G = linearly_reductive_group(:SL, 2, QQ);

julia> r = representation_on_forms(G, 2);

julia> S, x = graded_polynomial_ring(QQ, :x => 1:3);

julia> RG = invariant_ring(S, r);

julia> A, AtoS = affine_algebra(RG)
(Quotient of multivariate polynomial ring by ideal (0), Hom: A -> S)
```
"""
function affine_algebra(R::RedGroupInvarRing)
  if !isdefined(R, :presentation)
    V = fundamental_invariants(R)
    s = length(V)
    weights_ = zeros(Int, s)
    for i in 1:s
      weights_[i] = total_degree(V[i])
    end
    S, _ = graded_polynomial_ring(
      coefficient_ring(R), :t => 1:s; weights=weights_, cached=false
    )
    R_ = polynomial_ring(R)
    StoR = hom(S, R_, V)
    I = kernel(StoR)
    Q, StoQ = quo(S, I)
    QtoR = hom(Q, R_, V)
    R.presentation = QtoR
  end
  return domain(R.presentation), R.presentation
end

# Algorithm 4.5.1 in [DK15]
# Compute generators of the invariant ring without a Reynolds operator: the
# invariants of the degrees of the generators of the null cone ideal I generate
# the invariant ring. Here b is the ideal returned by proj_of_image_ideal and
# ringg is the ring in which we must return the invariants.
function inv_gens_no_reynolds(I::MPolyIdeal, b::MPolyIdeal, ringg::MPolyRing)
  n = ngens(ringg)
  mixed_ring_xy = base_ring(b)
  phi = hom(
    mixed_ring_xy, ringg, vcat(gens(ringg), [0 for i in (n + 1):ngens(mixed_ring_xy)])
  )

  degrees = sort!(unique!(map(total_degree, gens(I))))
  ans_vect = Vector{elem_type(ringg)}()
  for d in degrees
    append!(ans_vect, map(phi, basis_no_reynolds(d, n, b)))
  end
  return ans_vect
end

# Compute a K-basis of the invariants of degree d in the first n variables x of
# base_ring(b), a ring with variables x(1:n), y(1:n) and zz(1:?).
# A polynomial h in x is invariant if and only if h(x) - h(y) is in b.
function basis_no_reynolds(d::Int, n::Int, b::MPolyIdeal)
  mixed_ring = base_ring(b)
  xyz = gens(mixed_ring)
  x_to_y = hom(mixed_ring, mixed_ring, vcat(xyz[(n + 1):(2 * n)], xyz[(n + 1):end]))

  H = collect(monomials_of_degree(mixed_ring, d, 1:n))
  polys = normal_form([m - x_to_y(m) for m in H], b)

  #finding the generators of the kernel space
  V, VtoPoly = vector_space(base_ring(mixed_ring), polys)
  W = vector_space(base_ring(mixed_ring), length(polys))
  h = hom(W, V, [Oscar.preimage(VtoPoly, f) for f in polys])
  K, KtoW = kernel(h)
  alpha = KtoW.(gens(K))
  ans = Vector{elem_type(mixed_ring)}()
  for i in 1:length(alpha)
    pol = mixed_ring()
    for j in 1:length(alpha[i].v)
      pol += alpha[i][j] * H[j]
    end
    push!(ans, pol)
  end
  return ans
end
