include("NewMonomial-test.jl")
include("RootConversion-test.jl")
include("MainAlgorithm-test.jl")
include("DemazureOperators-test.jl")
include("LieAlgebras-test.jl")
include("MainAlgorithm-subroutines-test.jl")
include("VectorDemazure-test.jl")
include("WeylPolytope-test.jl")