# Export list for the Digraphs experimental module.
# Every exported name corresponds to a public function defined in the module;
# internal helpers (prefixed with `_`) are not exported.

export Digraph
export nv
export ne

# --- Section 3.1: creating digraphs ---------------------------------------
export is_digraph
export is_mutable_digraph
export is_immutable_digraph
export is_cayley_digraph
export is_digraph_with_adjacency_function
export digraph_by_out_neighbours_type
export digraph_family
export digraph
export digraph_from_adjacency_matrix
export digraph_from_edges
export edge_orbit_digraph
export digraph_from_in_neighbours
export digraph_from_in_neighbors
export cayley_digraph
export list_named_digraphs

# --- Section 3.2: changing representations ---------------------------------
export as_binary_relation
export as_digraph
export to_grape_graph
export as_grape_graph
export as_transformation

# --- Section 3.3: new digraphs from old ------------------------------------
export digraph_immutable_copy
export digraph_mutable_copy
export digraph_copy_same_mutability
export digraph_copy
export digraph_immutable_copy_if_immutable
export digraph_immutable_copy_if_mutable
export digraph_mutable_copy_if_mutable
export digraph_mutable_copy_if_immutable
export induced_subdigraph
export reduced_digraph
export reduced_digraph_attr
export maximal_symmetric_subdigraph
export maximal_symmetric_subdigraph_attr
export maximal_symmetric_subdigraph_without_loops
export maximal_symmetric_subdigraph_without_loops_attr
export maximal_anti_symmetric_subdigraph
export maximal_anti_symmetric_subdigraph_attr
export undirected_spanning_forest
export undirected_spanning_forest_attr
export undirected_spanning_tree
export undirected_spanning_tree_attr
export digraph_shortest_path_spanning_tree
export quotient_digraph
export digraph_reverse
export digraph_reverse_attr
export digraph_dual
export digraph_dual_attr
export digraph_symmetric_closure
export digraph_symmetric_closure_attr
export digraph_transitive_closure
export digraph_transitive_closure_attr
export digraph_reflexive_transitive_closure
export digraph_reflexive_transitive_closure_attr
export digraph_transitive_reduction
export digraph_transitive_reduction_attr
export digraph_reflexive_transitive_reduction
export digraph_reflexive_transitive_reduction_attr
export digraph_add_vertex
export digraph_add_vertices
export digraph_add_edge
export digraph_add_edge_orbit
export digraph_add_edges
export digraph_remove_vertex
export digraph_remove_vertices
export digraph_remove_edge
export digraph_remove_edge_orbit
export digraph_remove_edges
export digraph_remove_loops
export digraph_remove_loops_attr
export digraph_remove_all_multiple_edges
export digraph_remove_all_multiple_edges_attr
export digraph_contract_edge
export digraph_reverse_edges
export digraph_reverse_edge
export digraph_disjoint_union
export digraph_edge_union
export digraph_join
export digraph_cartesian_product
export digraph_direct_product
export conormal_product
export homomorphic_product
export lexicographic_product
export digraph_lexicographic_product
export modular_product
export digraph_modular_product
export strong_product
export digraph_strong_product
export digraph_cartesian_product_projections
export digraph_direct_product_projections
export line_digraph
export edge_digraph
export line_undirected_digraph
export edge_undirected_digraph
export double_digraph
export bipartite_double_digraph
export digraph_add_all_loops
export digraph_add_all_loops_attr
export distance_digraph
export digraph_closure
export digraph_mycielskian
export digraph_mycielskian_attr

# --- Section 3.4: random digraphs ------------------------------------------
export random_digraph
export random_multi_digraph
export random_tournament
export random_lattice

# --- Section 3.5: standard examples ----------------------------------------
export andrasfai_graph
export banana_tree
export binary_tree
export binomial_tree_graph
export bishops_graph
export bishop_graph
export bondy_graph
export book_graph
export burnt_pancake_graph
export pancake_graph
export stacked_book_graph
export chain_digraph
export circulant_graph
export complete_digraph
export complete_bipartite_digraph
export complete_multipartite_digraph
export cycle_digraph
export digraph_cycle
export cycle_symmetric_digraph
export empty_digraph
export null_digraph
export gear_graph
export haar_graph
export halved_cube_graph
export hanoi_graph
export helm_graph
export hypercube_graph
export johnson_digraph
export keller_graph
export kings_graph
export kneser_graph
export knights_graph
export lindgren_sousselier_graph
export lollipop_graph
export mobius_ladder_graph
export mycielski_graph
export odd_graph
export path_graph
export permutation_star_graph
export petersen_digraph
export generalised_petersen_graph
export prism_graph
export stacked_prism_graph
export queens_graph
export queen_graph
export rooks_graph
export rook_graph
export square_grid_graph
export grid_graph
export triangular_grid_graph
export star_graph
export tadpole_graph
export walsh_hadamard_graph
export web_graph
export wheel_graph
export windmill_graph
export edge_weighted_digraph

# --- Attributes -------------------------------------------------------------
export adjacency_matrix
export articulation_points
export boolean_adjacency_matrix
export bridges
export characteristic_polynomial
export chromatic_number
export clique_number
export degree_matrix
export digraph_absorption_expected_steps
export digraph_absorption_probabilities
export digraph_all_simple_circuits
export digraph_bicomponents
export digraph_connected_component
export digraph_connected_components
export digraph_core
export digraph_cycle_basis
export digraph_degeneracy
export digraph_degeneracy_ordering
export digraph_diameter
export digraph_dijkstra
export digraph_edges
export digraph_girth
export digraph_group
export digraph_hash
export digraph_join_table
export digraph_layers
export digraph_longest_simple_circuit
export digraph_loops
export digraph_maximal_matching
export digraph_maximum_flow
export digraph_maximum_matching
export digraph_meet_table
export digraph_minimum_cut
export digraph_minimum_cut_set
export digraph_nr_adjacencies
export digraph_nr_adjacencies_without_loops
export digraph_nr_connected_components
export digraph_nr_loops
export digraph_nr_strongly_connected_components
export digraph_odd_girth
export digraph_path
export digraph_period
export digraph_range
export digraph_shortest_distance
export digraph_shortest_path
export digraph_sinks
export digraph_source
export digraph_sources
export digraph_strongly_connected_component
export digraph_strongly_connected_components
export digraph_topological_sort
export digraph_undirected_girth
export digraph_vertex_connectivity
export digraph_vertices
export edge_weights
export edge_weighted_digraph_minimum_spanning_tree
export edge_weighted_digraph_shortest_path
export edge_weighted_digraph_shortest_paths
export edge_weighted_digraph_total_weight
export generators_of_cayley_digraph
export graph6_string
export group_of_cayley_digraph
export hamiltonian_path
export has_edge
export has_vertex
export in_degrees
export in_neighbours
export is_reachable
export laplacian_matrix
export minimal_cyclic_edge_cut
export non_lower_semimodular_pair
export non_upper_semimodular_pair
export nr_spanning_trees
export out_degrees
export out_neighbours
export shortest_distances
export sparse6_string
export strong_orientation

# --- Properties -------------------------------------------------------------
export has_loops
export has_no_vertices
export is_2_edge_transitive
export is_acyclic
export is_antisymmetric
export is_aperiodic
export is_biconnected
export is_bipartite
export is_bridgeless
export is_cayley
export is_chain
export is_cograph
export is_complete
export is_complete_bipartite
export is_complete_multipartite
export is_connected
export is_cycle
export is_digraph_core
export is_directed_forest
export is_directed_tree
export is_distance_regular
export is_distributive_lattice
export is_edge_transitive
export is_empty
export is_equivalence
export is_eulerian
export is_functional
export is_hamiltonian
export is_in_regular
export is_join_semilattice
export is_lattice
export is_lower_semimodular
export is_meet_semilattice
export is_modular_lattice
export is_multi
export is_negative_edge_weighted
export is_nonempty
export is_null
export is_out_regular
export is_outer_planar
export is_partial_order
export is_permutation
export is_planar
export is_preorder
export is_reflexive
export is_regular
export is_strongly_connected
export is_symmetric
export is_tournament
export is_transitive
export is_undirected_forest
export is_undirected_tree
export is_upper_semimodular
export is_vertex_transitive

# --- Isomorphisms -----------------------------------------------------------
export is_isomorphic
export automorphism_group
export bliss_automorphism_group
export bliss_canonical_labelling
