################################################################################
## Constructors for DeterminantalGerm
################################################################################

#TODO: To add more constructors (mostly snake_case constructors with embedding)


#TODO: Docstring for this constructor
function DeterminantalGerm(A::MatElem{T}, t::Int;
                           mat_type::Symbol = :generic, check::Bool=true
)  where T <: AbsLocalizedRingElem{<:Ring, <:RingElem, <:MPolyComplementOfKPointIdeal}
  @req mat_type in (:generic, :symmetric, :skew_symmetric) "'mat_type' must be either ':generic', ':symmetric' or 'skew_symmetric'"
  (n, m) = size(A)
  @req (1 <= t <= min(n, m)) "'t' must be in the range of 1:minimum(size(A))"
  L = base_ring(A)  
  val_type = Val{mat_type}
  I = _determinantal_ideal(A, t, val_type)

  @check (krull_dim(L) - krull_dim(I) == _expected_codim(n, m, t, val_type)) _codim_error(val_type)
  # The necessary check has already been done, if check=true, therefore check=false.
  X_A = DeterminantalGerm(spec(quo(L, I)[1]), A, t, mat_type=mat_type, check=false)
  # cache the already computed 'determinantal_ideal'
  set_attribute!(X_A, :determinantal_ideal, I)
  return X_A
end



@doc raw"""
    DeterminantalGerm(A::MatElem{<:MPolyRingElem}, t::Int, p::Vector{T}; mat_type::Symbol = :generic, check::Bool=true)

Return the DeterminantalGerm $(X_A^t, p)$, if it has the expected codimension, and throw an error otherwise.
!!! note
    If `check` is set to false, the codimension of the germ generated by the specified determinantal respectively pfaffian ideal of `A` is not checked to have the expected codimension and then might be wrongly assumed in further calculations.

# Examples:
```jldoctest
julia> R, (v,w,x,y,z) = QQ[:v,:w,:x,:y,:z];

julia> A = R[v w x y;  w x y z]
[v   w   x   y]
[w   x   y   z]

julia> B = R[v w x;  w x y;  x y z]
[v   w   x]
[w   x   y]
[x   y   z]

julia> X_A = DeterminantalGerm(A, 2, [0,0,0,0,0])
Spectrum
  of localization
    of quotient
      of multivariate polynomial ring in 5 variables v, w, x, y, z
        over rational field
      by ideal (v*x - w^2, v*y - w*x, w*y - x^2, v*z - w*y, w*z - x*y, x*z - y^2)
    at complement of maximal ideal of point (0, 0, 0, 0, 0)

julia> X_B = DeterminantalGerm(B, 2, [0,0,0,0,0], mat_type = :symmetric)
Spectrum
  of localization
    of quotient
      of multivariate polynomial ring in 5 variables v, w, x, y, z
        over rational field
      by ideal (v*x - w^2, v*y - w*x, w*y - x^2, v*y - w*x, v*z - x^2, w*z - x*y, w*y - x^2, w*z - x*y, x*z - y^2)
    at complement of maximal ideal of point (0, 0, 0, 0, 0)

julia> X_A == X_B
false

julia> SpaceGerm(representative(X_A), point(X_A)) == SpaceGerm(representative(X_B), point(X_B))
true
```
"""
function DeterminantalGerm(A::MatElem{<:MPolyRingElem}, t::Int, p::Vector{T};
                           mat_type::Symbol = :generic, check::Bool=true
                          ) where T<:Union{Integer, FieldElem}
  R = base_ring(A)
  kk = coefficient_ring(R)
  point = [kk.(v) for v in p]  ## throws an error, if vector entries are not compatible
  L, _ = localization(R, complement_of_point_ideal(R, point))
  return DeterminantalGerm(L.(A), t, mat_type=mat_type, check=check)
end
