######################################
@doc raw"""
    blowup(i::AbstractVarietyMap; symbol::String="e")

Given an inclusion `i`$ : $ `X` $\rightarrow$ `Y`, say, return the blow-up of `Y` along `X`.

More precisely, return a tuple `(Bl, E, j)`, say, where
- `Bl`, an abstract variety, is the blow-up,
- `E`, an abstract variety, is the exceptional divisor, and
- `j`, a map of abstract varieties, is the inclusion of `E` into `Bl`.

!!! note
    The resulting maps `Bl` $\rightarrow$ `Y` and `E` $\rightarrow$ `X` are obtained by entering `structure_map(Bl)` and `structure_map(E)`, respectively.

# Examples

*Taken from the sage package Chow by Lehn/Sorger:*

```jldoctest
julia> P2xP2 = abstract_projective_space(2, symbol = "k")*abstract_projective_space(2, symbol = "l")
AbstractVariety of dim 4

julia> P8 = abstract_projective_space(8)
AbstractVariety of dim 8

julia> k, l = gens(P2xP2)
2-element Vector{MPolyQuoRingElem{MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}}}:
 k
 l

julia> Se = map(P2xP2, P8, [k+l])
AbstractVarietyMap from AbstractVariety of dim 4 to AbstractVariety of dim 8

julia> Bl, E, j = blowup(Se)
(AbstractVariety of dim 8, AbstractVariety of dim 7, AbstractVarietyMap from AbstractVariety of dim 7 to AbstractVariety of dim 8)

julia> betti_numbers(Bl)
9-element Vector{Int64}:
 1
 2
 4
 7
 8
 7
 4
 2
 1

```

*The Steiner problem:*

```jldoctest
julia> P2 = abstract_projective_space(2)
AbstractVariety of dim 2

julia> P5 = abstract_projective_space(5, symbol = "H")
AbstractVariety of dim 5

julia> h = gens(P2)[1]
h

julia> H = gens(P5)[1]
H

julia> i = map(P2, P5, [2*h])
AbstractVarietyMap from AbstractVariety of dim 2 to AbstractVariety of dim 5

julia> Bl, E, j = blowup(i)
(AbstractVariety of dim 5, AbstractVariety of dim 4, AbstractVarietyMap from AbstractVariety of dim 4 to AbstractVariety of dim 5)

julia> e, HBl = gens(chow_ring(Bl))
2-element Vector{MPolyQuoRingElem{MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}}}:
 e
 H

julia> integral((6*HBl-2*e)^5)
3264

```
"""
function blowup(i::AbstractVarietyMap; symbol::String="e")
  # use construction via generators and relations as in [EH16](@cite), Section 13.6
  #  E ---j---> Bl
  #  |          |
  #  g          f
  #  |          |
  #  Z ---i---> X

  SED = symbol # SED = "e"
  Z, X = domain(i), codomain(i)
  AZ, RZ = chow_ring(Z), base_ring(chow_ring(Z))
  AX, RX = chow_ring(X), base_ring(chow_ring(X))

  # we write N for the normal bundle N_{ZX}

  N = -tangent_bundle(i) # normal bundle
  codimension = rank(N) # codimension of Z in X
  codimension <= 0 && error("not a proper subvariety")

  # we construct E as the projective bundle PN of N, see [EH16](@cite), page 472

  E = projective_bundle(N)
  AE, RE = chow_ring(E), base_ring(chow_ring(E))
  g = structure_map(E)
  zeta = polarization(g)  # the first Chern class of O_E(1)

  # we set up the generators of ABl

  # we first represent AZ as an AX-module

  gs, PM, sect = present_finite_extension_ring(pullback_morphism(i))
  # the finite `AX`-module` `AZ`, `present_finite_extension_ring` returns
  # * a vector `gs` of polynomials representing generators for `AZ` as an `AX`-module,
  # * a matrix `PM` of relations, and
  # * a vector `sect` of sections of the projection `AX^n -> AZ` (where `n = length(gs)`)
  #   which sends the `i`-th standard basis vector to `gs[i]`.
  # write Z(gs[i]) for the class in AZ represented by gs[i]
  # if e[i] = j_push_g_pull(Z(gs[i])), then e[end] is the class of the exceptional divisor in ABl;
  # here, present_finite_extension_ring needs to return the generators accordingly;
  # that is, Z(gs[end]) must be the generator 1_{AZ}; note that zeta = -j_pull(e[end]).

  # by [EH16](@cite), Proposition 13.12, ABl is generated by j_push(AE) and f_pull(AX) as a K-algebra;
  # equivalently, as an AX-algebra, ABl is generated by the e[i], so we add these as new variables
  ngs = length(gs)
  syms = ["$SED[$i]" for i in 1:(ngs - 1)]
  push!(syms, SED)
  degrees = [degree(Int, Z(gs[i])) + 1 for i in 1:ngs]
  degrees_RX = [Int(degree(g)[1]) for g in gens(RX)]
  RBl, e_vars, x_vars = graded_polynomial_ring(
    base(X), syms, symbols(RX); weights=vcat(degrees, degrees_RX)
  )

  RXtoRBl = Oscar.hom(RX, RBl, x_vars) # f_pull on polynomial ring level
  j_push_g_pull = x -> sum(e_vars .* RXtoRBl.(sect(x.f))) # AZ --> RBl

  # we set up the relations of ABl
  relations = elem_type(RBl)[]

  # 1) relations from AX
  isdefined(AX, :I) && append!(relations, RXtoRBl.(gens(AX.I)))

  # 2) relations for AZ as an AX-module
  append!(relations, RXtoRBl.(PM) * e_vars)

  # 3) relation from AE: sum g_pull(c_k(N)) * zeta^(d-k) = 0, see [EH16](@cite), Theorem 9.6
  cN = total_chern_class(N)[0:codimension] # cN[k] = c_(k-1)(N)
  push!(
    relations,
    sum([
      j_push_g_pull(cN[k + 1]) * (-e_vars[end])^(codimension - k) for k in 0:codimension
    ]),
  )

  # 4) j_push(x) * j_push(y) = -j_push(x * y * zeta) # rule for multiplication, [EH16](@cite), Proposition 13.12
  # recall that e[i] = j_push_g_pull(Z(gs[i]))
  for j in 1:(ngs - 1), k in j:(ngs - 1)
    push!(
      relations, e_vars[j] * e_vars[k] + j_push_g_pull(Z(gs[j] * Z(gs[k]))) * (-e_vars[end])
    )
  end

  # 5) relation as in the proof of [EH16](@cite), Theorem 13.14:
  # RXtoRBl(i_push(x)) = j_push(g_pull(x) * ctop(Q)) where Q is the tautological quotient bundle on E
  # we have ctop(Q) = sum g_pull(c_{k-1}(N)) * zeta^(d-k), [EH16](@cite), page 477
  for j in 1:ngs
    lhs = RXtoRBl(pushforward(i, Z(gs[j])).f) # this is the crucial step where i_push is needed
    rhs = sum([
      j_push_g_pull(Z(gs[j]) * cN[k]) * (-e_vars[end])^(codimension - k) for
      k in 1:codimension
    ])
    push!(relations, lhs - rhs)
  end

  relations = minimal_generating_set(ideal(RBl, relations))
  ABl, _ = quo(RBl, relations)
  Bl = abstract_variety(dim(X), ABl)

  # Bl and g being constructed, we set up the morphisms f and j

  # pushforward of f and more
  RBltoRX = Oscar.hom(RBl, RX, vcat(repeat([RX()], ngs), gens(RX)))
  f_pushforward = x -> (xf=simplify(x).f; X(RBltoRX(xf)))
  f_pushforward = MapFromFunc(ABl, AX, f_pushforward)
  f = AbstractVarietyMap(Bl, X, Bl.(x_vars), f_pushforward)
  Bl.structure_map = f
  if isdefined(X, :point)
    Bl.point = pullback(f, point_class(X))
  end

  # pullback of j
  j_pull = vcat(
    [-zeta * pullback(g, Z(xi)) for xi in gs],
    [pullback(g, pullback(i, f)) for f in gens(AX)],
  )

  # pushforward of j: write as a polynomial in zeta, and compute term by term
  REtoRZ = Oscar.hom(RE, RZ, pushfirst!(gens(RZ), RZ()))
  j_push =
    x -> (xf=simplify(x).f;
      ans=RBl();
      for k in (codimension - 1):-1:0
        q = div(xf, zeta.f^k)
        ans += j_push_g_pull(Z(REtoRZ(q))) * (-e_vars[end])^k
        xf -= q * zeta.f^k
      end;
      Bl(ans))
  j_push = MapFromFunc(AE, ABl, j_push)
  j = AbstractVarietyMap(E, Bl, j_pull, j_push)

  # the normal bundle of E in Bl is O(-1)
  j.T = -tautological_bundles(E)[1]

  # finally, compute the tangent bundle of Bl:
  # 0 -> Bl.T -> RXtoRBl(X.T) -> j_*(Q) -> 0 where Q is the tautological quotient bundle
  f.T = -pushforward(j, tautological_bundles(E)[2])
  Bl.T = pullback(f, tangent_bundle(X)) + tangent_bundle(f)

  # chern(Bl.T) can be readily computed from its Chern character, but the following is faster
  alpha = sum(
    sum(
      (binomial(ZZ(codimension - j), ZZ(k)) - binomial(ZZ(codimension - j), ZZ(k + 1))) *
      zeta^k for
      k in 0:(codimension - j)
    ) * pullback(g, chern_class(N, j)) for j in 0:codimension
  )
  Bl.T.chern = simplify(
    pullback(f, total_chern_class(tangent_bundle(X))) +
    pushforward(j, pullback(g, total_chern_class(tangent_bundle(Z))) * alpha),
  )
  set_attribute!(E, :projections => [j, g])
  set_attribute!(Bl, :exceptional_divisor => E)
  set_attribute!(Bl, :description => "Blow-up of $X with center $Z")
  if get_attribute(Z, :alg) == true && get_attribute(X, :alg) == true
    set_attribute!(Bl, :alg => true)
  end
  return Bl, E, j
end

@doc raw"""
    function blowup_points(X::AbstractVariety, n::Int; symbol::String = "e")

Return the blow-up of `X` at `n` points.

# Examples
```jldoctest
julia> P2 = abstract_projective_space(2)
AbstractVariety of dim 2

julia> Bl = blowup_points(P2, 1)
AbstractVariety of dim 2

julia> chow_ring(Bl)
Quotient
  of multivariate polynomial ring in 2 variables over QQ graded by
    e -> [1]
    h -> [1]
  by ideal (e*h, e^2 + h^2)

```
"""
function blowup_points(X::AbstractVariety, n::Int; symbol::String="e")
  SED = symbol # SED = "e"
  if n == 1
    symbs = [SED]
  else
    symbs = ["$SED[$i]" for i in 1:n]
  end
  Bl = X
  P = abstract_point(; base=base(X))
  for i in 1:n
    Bl = blowup(map(P, Bl, [zero(chow_ring(P)) for j in 1:i]); symbol=symbs[i])[1]
  end
  set_attribute!(Bl, :description => "Blow-up of $X at $n points")
  Bl.structure_map = map(Bl, X)
  if get_attribute(X, :alg) == true
    set_attribute!(Bl, :alg => true)
  end
  return Bl
end

@doc raw"""
    extend_inclusion(i::AbstractVarietyMap; symbol::String = "x")

Given an inclusion $i\colon X \hookrightarrow Y$ where the class of $X$ in $\mathrm{N}^*(Y)_{\mathbb Q}$
is not already representable in $\mathrm{N}^*(Y)_{\mathbb Q}$, create a modified version $Y^+$ of $Y$
with extra classes added to the Chow ring so that one can pushforward all classes on $X$.

Return the resulting morphism $j\colon X \to Y^+$.

!!! note
    The string `symbol` specifies how the extra generators in the extended Chow ring $\mathrm{N}^*(X^+)_{\mathbb Q}$ are printed.

See the subsection [Example: Cubic fourfolds](@ref) of the documentation for an example.
"""
function extend_inclusion(i::AbstractVarietyMap; symbol::String="x")
  ###############################################################################
  #
  # given an AbsVarietyHom i:Z -> X, declare that it is an inclusion and return a
  # new one where pushforward is possible, by adding the extra classes to X
  # this results in a modified Xplus which represents the same variety X but
  # contains more classes
  #
  #     j  Xplus f
  #      ↗      ↘
  #    Z ———i———→ X
  #
  # specifically,
  # A*Z is generated as an A*X-module by gs[1], ..., gs[ngs], computed using `present_finite_extension_ring`
  # A*Xplus is generated as an A*X-algebra by the images of these generators under j_push, ev[i] = j_push(gs[i])
  #
  ###############################################################################
  #
  SED = symbol # SED = "x"
  Z, X = domain(i), codomain(i)
  AX, RX = chow_ring(X), base_ring(chow_ring(X))

  # we write N for the normal bundle N_{ZX}

  N = -tangent_bundle(i) # normal bundle
  codimension = rank(N) # codimension of Z in X
  codimension <= 0 && error("not a proper subvariety")
  c = top_chern_class(N)

  gs, PM, sect = present_finite_extension_ring(pullback_morphism(i))
  ngs = length(gs)

  # similar to blowup: the last variable below is the class of Z in Xplus
  syms = ["$SED[$i]" for i in 1:(ngs - 1)]
  push!(syms, SED)
  degrees = [Oscar.degree(Int, Z(gs[i])) + codimension for i in 1:ngs]
  degrees_RX = [Int(Oscar.degree(g)[1]) for g in gens(RX)]
  RXplus, e_vars, x_vars = graded_polynomial_ring(
    base(X), syms, symbols(RX); weights=vcat(degrees, degrees_RX)
  )
  RXtoRXplus = Oscar.hom(RX, RXplus, x_vars) # f_pull on polynomial ring level
  j_push = x -> sum(e_vars .* RXtoRXplus.(sect(x.f))) # AZ --> RXplus

  # we set up the relations of AXplus
  relations = elem_type(RXplus)[]

  # 1) relations from AX
  isdefined(AX, :I) && append!(relations, RXtoRXplus.(gens(AX.I)))

  # 2) relations for AZ as an AX-module
  append!(relations, RXtoRXplus.(PM) * e_vars)

  # 3) j_push(x) * j_push(y) = j_push(x * y * c)
  for j in 1:ngs, k in j:ngs
    push!(relations, e_vars[j] * e_vars[k] - j_push(Z(gs[j]) * Z(gs[k]) * c))
  end

  # 4) the points are the same
  if isdefined(Z, :point) && isdefined(X, :point)
    push!(relations, RXtoRXplus(point_class(X).f) - j_push(point_class(Z)))
  end

  relations = minimal_generating_set(ideal(RXplus, relations))
  AXplus, _ = quo(RXplus, relations)
  Xplus = abstract_variety(dim(X), AXplus)

  # X and Xplus are the same variety
  set_attribute!(Xplus, :description => "$X")
  # but Xplus has more classes; we set up the morphism f: Xplus -> X as the identity on the level of varieties, and the natural map on Chow rings
  # f_pushforward works as follows:
  # * simplify(x) reduces x modulo the ideal of AXplus; crucially, relation (3) above
  #   (the self-intersection formula e[j]*e[k] = j_push(gs[j]*gs[k]*c)) rewrites products
  #   of e_vars into x_vars, encoding the pushforward classes i_*(gs[j]) in A*(X)
  # * RXplustoRX then sends the x_vars to the corresponding generators of RX (identity on A*(X))
  #   and any e_vars that survive simplify to 0, which is correct since those classes have
  #   degree exceeding dim(X) and thus no image in A*(X)
  RXplustoRX = Oscar.hom(RXplus, RX, vcat(repeat([RX()], ngs), gens(RX)))
  f_pushforward = MapFromFunc(
    chow_ring(Xplus), chow_ring(X), x -> (xf=simplify(x).f; X(RXplustoRX(xf)))
  )
  f = AbstractVarietyMap(Xplus, X, Xplus.(x_vars), f_pushforward)
  Xplus.structure_map = f
  Xplus.T = pullback(f, tangent_bundle(X))
  f.T = AbstractBundle(Xplus, Xplus(0)) # there is no relative tangent bundle
  if isdefined(X, :point)
    Xplus.point = pullback(f, point_class(X))
  end
  if isdefined(X, :O1)
    Xplus.O1 = pullback(f, polarization(X))
  end
  j_pullback = vcat(Z.(gs) .* c, [pullback(i, f) for f in gens(AX)])
  j_pushforward = MapFromFunc(chow_ring(Z), chow_ring(Xplus), x -> Xplus(j_push(x)))
  j = AbstractVarietyMap(Z, Xplus, j_pullback, j_pushforward)
  return j
end
