include("integer-test.jl")
include("rational-test.jl")
include("mpoly-test.jl")
include("orderings-test.jl")
include("affine-alghom-test.jl")
include("mpoly-graded-test.jl")
include("mpoly-local-test.jl")
include("mpoly-localizations.jl")
include("mpolyquo-localizations.jl")
include("integer-localizations.jl")
include("nmod-localizations.jl")
include("mpoly-nested-test.jl")
include("MPolyQuo_test.jl")
include("groebner-test.jl")
include("msolve-test.jl")
include("FractionalIdeal-test.jl")
include("mpoly_affine_algebras_test.jl")
include("slpolys-test.jl")

include("NumberField.jl")
include("FunctionField-test.jl")
include("AbelianClosure.jl")

include("MPolyAnyMap/MPolyRing.jl")
include("MPolyAnyMap/MPolyQuo.jl")
include("MPolyAnyMap/AffineAlgebras.jl")

include("GAlgebra-test.jl")
include("FreeAssAlgIdeal-test.jl")

include("binomial-ideals-test.jl")
