# Deprecated after 0.14.*
Base.@deprecate_binding is_isomorphic_with_symmetric_group is_isomorphic_to_symmetric_group
Base.@deprecate_binding has_is_isomorphic_with_symmetric_group has_is_isomorphic_to_symmetric_group
Base.@deprecate_binding set_is_isomorphic_with_symmetric_group set_is_isomorphic_to_symmetric_group

Base.@deprecate_binding is_isomorphic_with_alternating_group is_isomorphic_to_alternating_group
Base.@deprecate_binding has_is_isomorphic_with_alternating_group has_is_isomorphic_to_alternating_group
Base.@deprecate_binding set_is_isomorphic_with_alternating_group set_is_isomorphic_to_alternating_group

Base.@deprecate_binding proj_space projective_space

Base.@deprecate_binding are_algebraically_independent is_algebraically_independent_with_relations

Base.@deprecate ambient_ring(U::AbsMultSet) ring(U)

Base.@deprecate_binding hall_subgroups_representatives hall_subgroup_reps
Base.@deprecate_binding hasrelshp has_relshp
Base.@deprecate_binding hastorusfactor has_torusfactor
Base.@deprecate_binding inner_automorphisms_group inner_automorphism_group
Base.@deprecate_binding isaffine is_affine
Base.@deprecate_binding isalmostsimple is_almost_simple
Base.@deprecate_binding isample is_ample
Base.@deprecate_binding isbicoset is_bicoset
Base.@deprecate_binding isbinomial is_binomial
Base.@deprecate_binding isbounded is_bounded
Base.@deprecate_binding iscartier is_cartier
Base.@deprecate_binding iscellular is_cellular
Base.@deprecate_binding iscomplete is_complete
Base.@deprecate_binding iscongruent is_congruent
Base.@deprecate_binding isconjugate_subgroup is_conjugate_subgroup
Base.@deprecate_binding isdecorated is_decorated
Base.@deprecate_binding isdihedral_group is_dihedral_group
Base.@deprecate_binding isfano is_fano
Base.@deprecate_binding isfeasible is_feasible
Base.@deprecate_binding isfiltered is_filtered
Base.@deprecate_binding isfinite_order is_finiteorder
Base.@deprecate_binding isfinitelygenerated is_finitely_generated
Base.@deprecate_binding isfull_direct_product is_full_direct_product
Base.@deprecate_binding isfull_semidirect_product is_full_semidirect_product
Base.@deprecate_binding isfull_wreath_product is_full_wreath_product
Base.@deprecate_binding isfulldimensional is_fulldimensional
Base.@deprecate_binding isgenerated_by_standard_unit_vectors is_generated_by_standard_unit_vectors
Base.@deprecate_binding isglobal is_global
Base.@deprecate_binding isgraded is_graded
Base.@deprecate_binding isinner_automorphism is_inner_automorphism
Base.@deprecate_binding isinvariant is_invariant
Base.@deprecate_binding isisomorphic_with_alternating_group is_isomorphic_to_alternating_group
Base.@deprecate_binding isisomorphic_with_symmetric_group is_isomorphic_to_symmetric_group
Base.@deprecate_binding isleft is_left
Base.@deprecate_binding islocal is_local
Base.@deprecate_binding ismixed is_mixed
Base.@deprecate_binding ismolien_series_implemented is_molien_series_implemented
Base.@deprecate_binding isnatural_alternating_group is_natural_alternating_group
Base.@deprecate_binding isnatural_symmetric_group is_natural_symmetric_group
Base.@deprecate_binding isnef is_nef
Base.@deprecate_binding isobviouslyabelian is_obviously_abelian false
Base.@deprecate_binding isorbifold is_orbifold
Base.@deprecate_binding isperfect is_perfect
Base.@deprecate_binding ispgroup is_pgroup
Base.@deprecate_binding ispointed is_pointed
Base.@deprecate_binding isprojective is_projective
Base.@deprecate_binding ispure is_pure
Base.@deprecate_binding isquaternion_group is_quaternion_group
Base.@deprecate_binding isright is_right
Base.@deprecate_binding issemiregular is_semiregular
Base.@deprecate_binding issemisimple is_semisimple
Base.@deprecate_binding issimplicial is_simplicial
Base.@deprecate_binding issingular is_singular
#Base.@deprecate_binding issmooth_curve is_smooth_curve
Base.@deprecate_binding issolvable is_solvable
Base.@deprecate_binding issupersolvable is_supersolvable
Base.@deprecate_binding istransitive is_transitive
Base.@deprecate_binding isunipotent is_unipotent
Base.@deprecate_binding isunital is_unital
Base.@deprecate_binding iswelldefined is_welldefined
Base.@deprecate_binding representative_action is_conjugate_with_data
Base.@deprecate_binding representative_action_in_gl_or_sl is_conjugate_with_data_in_gl_or_sl

Base.@deprecate_binding has_isfinite has_is_finite
Base.@deprecate_binding SymmetricGroup symmetric_group

# Allow backwards compatibility after removal of Oscar.Graphs module.
const Graphs = Oscar

Base.@deprecate_binding MPolyElem_dec MPolyDecRingElem
Base.@deprecate_binding MPolyRing_dec MPolyDecRing
Base.@deprecate_binding MPolyLocalizedRingElem MPolyLocRingElem
Base.@deprecate_binding MPolyLocalizedRing MPolyLocRing
Base.@deprecate_binding MPolyQuoElem MPolyQuoRingElem
Base.@deprecate_binding MPolyQuo MPolyQuoRing
Base.@deprecate_binding MPolyQuoLocalizedRingElem MPolyQuoLocRingElem
Base.@deprecate_binding MPolyQuoLocalizedRing MPolyQuoLocRing
Base.@deprecate_binding SubQuoElem SubquoModuleElem
Base.@deprecate_binding SubQuo SubquoModule
#@alias SubQuoElem_dec SubquoDecModuleElem
#@alias SubQuo_dec SubquoDecModule
Base.@deprecate_binding GradedPolynomialRing graded_polynomial_ring


# Deprecated after 0.15
Base.@deprecate_binding _compute_glueing_base_change _compute_gluing_base_change
Base.@deprecate_binding _compute_inherited_glueing _compute_inherited_gluing
Base.@deprecate_binding _compute_toric_glueing _compute_toric_gluing
Base.@deprecate_binding add_glueing! add_gluing!
Base.@deprecate_binding base_glueing base_gluing
Base.@deprecate_binding glueing_domains gluing_domains
Base.@deprecate_binding glueing_graph gluing_graph
Base.@deprecate_binding glueing_morphisms gluing_morphisms
Base.@deprecate_binding glueings gluings
Base.@deprecate_binding inherit_glueings! inherit_gluings!
Base.@deprecate_binding is_connected_glueing is_connected_gluing
Base.@deprecate_binding pruned_glueing_graph pruned_gluing_graph
Base.@deprecate_binding underlying_glueing underlying_gluing
Base.@deprecate_binding update_glueing_graph update_gluing_graph
Base.@deprecate_binding AbsGlueing AbsGluing
Base.@deprecate_binding AbsProjectiveGlueing AbsProjectiveGluing
Base.@deprecate_binding BaseChangeGlueingData BaseChangeGluingData
Base.@deprecate_binding CoveredProjectiveGlueingData CoveredProjectiveGluingData
Base.@deprecate_binding Glueing Gluing
Base.@deprecate_binding InheritGlueingData InheritGluingData
Base.@deprecate_binding LazyProjectiveGlueing LazyProjectiveGluing
Base.@deprecate_binding ProjectiveGlueing ProjectiveGluing
Base.@deprecate_binding ProjectiveGlueingData ProjectiveGluingData
Base.@deprecate_binding SimpleGlueing SimpleGluing
Base.@deprecate_binding ToricGlueingData ToricGluingData

Base.@deprecate_binding jacobi_matrix jacobian_matrix
Base.@deprecate_binding jacobi_ideal jacobian_ideal

@deprecate embedding(G::DirectProductGroup, j::Int) canonical_injection(G, j)
@deprecate projection(G::DirectProductGroup, j::Int) canonical_projection(G, j)
@deprecate embedding(G::SemidirectProductGroup, n::Int) canonical_injection(G, n)
@deprecate projection(G::SemidirectProductGroup) canonical_projection(G)
@deprecate embedding(W::WreathProductGroup, n::Int) canonical_injection(W, n)
@deprecate projection(W::WreathProductGroup) canonical_projection(W)

@deprecate n_cones number_of_cones
@deprecate n_connected_components number_of_connected_components
@deprecate n_maximal_cells number_of_maximal_cells
@deprecate n_maximal_cones number_of_maximal_cones
@deprecate n_maximal_polyhedra number_of_maximal_polyhedra
@deprecate ne number_of_edges
@deprecate nv number_of_vertices
@deprecate num_partitions number_of_partitions
@deprecate num_positive_roots number_of_positive_roots
@deprecate num_roots number_of_roots
@deprecate num_simple_roots number_of_simple_roots
@deprecate num_standard_tableaux number_of_standard_tableaux
@deprecate number_atlas_groups number_of_atlas_groups
@deprecate number_conjugacy_classes number_of_conjugacy_classes
@deprecate has_number_conjugacy_classes has_number_of_conjugacy_classes
@deprecate set_number_conjugacy_classes set_number_of_conjugacy_classes
@deprecate number_moved_points number_of_moved_points
@deprecate has_number_moved_points has_number_of_moved_points
@deprecate set_number_moved_points set_number_of_moved_points
@deprecate number_perfect_groups number_of_perfect_groups
@deprecate has_number_perfect_groups has_number_of_perfect_groups
@deprecate number_primitive_groups number_of_primitive_groups
@deprecate has_number_primitive_groups has_number_of_primitive_groups
@deprecate number_small_groups number_of_small_groups
@deprecate has_number_small_groups has_number_of_small_groups
@deprecate number_transitive_groups number_of_transitive_groups
@deprecate has_number_transitive_groups has_number_of_transitive_groups
