function is_signature_based_gb_algorithm_applicable(I::MPolyIdeal, ordering::MonomialOrdering, signature_ordering::Symbol)
  return (ordering == degrevlex(base_ring(I)) && !is_graded(base_ring(I))
            && (coefficient_ring(I) isa FqField
                 && absolute_degree(coefficient_ring(I)) == 1
                 && characteristic(coefficient_ring(I)) < 2^31)
                 && (!(signature_ordering == :DPOT) || all(_is_homogeneous, gens(I)))
               )
end

@doc raw"""
  groebner_basis_signature_based(
    I::MPolyIdeal; info_level::Int=0, signature_ordering::Symbol=:POT
)

Returns a Gröbner basis of `I` w.r.t. to the
degree reverse lexicographical monomial ordering and the signature ordering
`signature_ordering`.

!!! note
  Only ground fields of characteristic `p`, `p` prime, `p < 2^{31}` are supported.

!!! note
  If `signature_ordering == :DPOT` then the input generators must be homogeneous.
  
!!! note
  The algorithms behaviour may depend heavily on how the elements in generators list are sorted.

!!! note
  In general, the resulting Gröbner basis is not reduced.

# Possible keyword arguments
- `info_level::Int=0`: info level printout: off (`0`, default), computational details (`1`)
- `signature_ordering::Symbol=:POT`: The module monomial ordering for the signatures, either `:POT` (position-over-term, default) or `:DPOT` (degree-position-over-term).

# Examples
```jldoctest
julia> R,(x,y) = polynomial_ring(GF(32003), [:x,:y])
(Multivariate polynomial ring in 2 variables over GF(32003), FqMPolyRingElem[x, y])

julia> I = ideal(R,[x^2+y,x*y+y^2-1])
Ideal generated by
  x^2 + y
  x*y + y^2 + 32002

julia> Oscar.groebner_basis_signature_based(I)
Gröbner basis with elements
  1: x^2 + y
  2: x*y + y^2 + 32002
  3: y^3 + y^2 + x + 32002*y
with respect to the ordering
  degrevlex([x, y])

julia> I = ideal(R,[x^2+y^2,x*y+y^2])
Ideal generated by
  x^2 + y^2
  x*y + y^2

julia> Oscar.groebner_basis_signature_based(I, signature_ordering=:DPOT)
Gröbner basis with elements
  1: x^2 + y^2
  2: x*y + y^2
  3: y^3
with respect to the ordering
  degrevlex([x, y])
```
"""
function groebner_basis_signature_based(
  I::MPolyIdeal;
  info_level::Int=0,
  signature_ordering::Symbol=:POT
)
  ordering = degrevlex(base_ring(I))
  AI = AlgebraicSolving.Ideal(oscar_generators(I))

  sig_gb = AlgebraicSolving.sig_groebner_basis(AI.gens,info_level=info_level, degbound=0, mod_ord=signature_ordering)
  # sig_gb includes the signatures and the elements are sorted w.r.t. the signatures. Thus we drop the signatures
  # and sort the generators w.r.t. degrevlex.
  gb = [g[2] for g in sig_gb]
  p = sortperm([leading_term(x) for x in gb]; order=degrevlex(base_ring(I)))

  GB = IdealGens(base_ring(I), gb[p], ordering, keep_ordering=false, isGB=true, isReduced=false)
  I.gb[ordering] = GB

  return GB
end
