# Cancel superfluous CI runs for pull requests. For details see
# <https://github.com/marketplace/actions/cancel-workflow-action>.
name: Cancel
on:
  workflow_run:
    workflows: ["Run tests", "Documentation"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.9.1
      with:
        all_but_latest: true
        workflow_id: ${{ github.event.workflow.id }}
